version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: vtuber-backend:latest
    ports:
      - "8765:8765"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=8765
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tts_finetune_app:
    build:
      context: .
      dockerfile: src/backend/tts_finetune_app/Dockerfile
    image: tts-finetune-app:latest
    volumes:
      - ./backend/tts_finetune_app/training_data:/app/backend/tts_finetune_app/training_data
      - ./backend/tts_finetune_app/checkpoints:/app/backend/tts_finetune_app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    command: bash

  ingest:
    image: tts-finetune-app:latest
    depends_on:
      - tts_finetune_app
    volumes:
      - ./backend/tts_finetune_app/training_data:/app/backend/tts_finetune_app/training_data
      - ./backend/tts_finetune_app/checkpoints:/app/backend/tts_finetune_app/checkpoints
    entrypoint: ["python", "backend/tts_finetune_app/scripts/ingest.py"]
    # Usage on Windows CMD:
    # docker-compose build
    # docker-compose run --rm ingest C:\path\to\your\input.mp3