version: '3.8'
services:
  chat_app:
    build:
      context: ..
      dockerfile: backend/chat_app/Dockerfile
      args:
        INSTALL_TORCH: "false" # set to "true" if you want torch installed in image
    environment:
      - PYTHONUNBUFFERED=1
      - RNNOISE_ENABLED=true
      - STREAMING_STT_MAX_CONCURRENT=1
    ports:
      - "8765:8765"
    volumes:
      - ..:/app:delegated
    restart: unless-stopped